import { AreaQueryType } from "./types";

export const AREA_TYPE_LABELS: Record<AreaQueryType, string> = {
  all: "🌐 所有面域",
  building: "🏢 建筑轮廓",
  landuse: "🗺️ 城市功能区",
  admin: "🏛️ 行政边界",
  poi_restaurant: "🍜 餐饮美食",
  poi_medical: "🏥 医疗设施",
  poi_transport: "🚌 交通设施",
  poi_shopping: "🛒 商业购物",
  poi_education: "🎓 教育设施",
  poi_sport: "⚽ 体育健身",
  poi_hotel: "🏨 住宿服务",
  poi_all: "📍 所有 POI",
};

export const AREA_TYPE_DESCRIPTIONS: Record<AreaQueryType, string> = {
  all: "同时提取建筑、城市功能区、行政边界等多种面域",
  building: "查询建筑物轮廓（如单体建筑、大型场馆）",
  landuse: "查询住宅区、商业区、公园绿地、工业用地等城市功能区",
  admin: "查询行政区划边界（省/市/区/街道）",
  poi_restaurant: "查询餐厅、咖啡馆、小吃店等餐饮场所",
  poi_medical: "查询医院、诊所、药店等医疗设施",
  poi_transport: "查询停车场、公交站、码头等交通设施",
  poi_shopping: "查询商场、超市、便利店等商业购物场所",
  poi_education: "查询学校、大学、幼儿园等教育设施",
  poi_sport: "查询体育场、运动中心、篮球场等体育设施",
  poi_hotel: "查询酒店、旅馆、民宿等住宿服务",
  poi_all: "查询所有类型的 POI 点位",
};

export const LANDUSE_STANDARD_MAP: Record<string, { name: string; color: string }> = {
  farmland: { name: "01 耕地", color: "#F5F8DC" },
  orchard: { name: "02 园地", color: "#BFE9AA" },
  vineyard: { name: "02 园地", color: "#BFE9AA" },
  wood: { name: "0301 乔木林地", color: "#68B167" },
  forest: { name: "03 林地", color: "#68B167" },
  grassland: { name: "0401 天然牧草地", color: "#83C238" },
  meadow: { name: "04 草地", color: "#83C238" },
  residential: { name: "0701 城镇住宅用地", color: "#FFFF2D" },
  apartments: { name: "0702 城镇住宅用地（公寓）", color: "#FFE600" },
  dormitory: { name: "0704 城镇住宅用地（宿舍）", color: "#FFEB3B" },
  house: { name: "0705 城镇住宅用地（住宅）", color: "#FFF176" },
  detached: { name: "0703 城镇住宅用地（独立住宅）", color: "#FFD700" },
  bungalow: { name: "0708 城镇住宅用地（平房）", color: "#FFF9C4" },
  terrace: { name: "0706 城镇住宅用地（排屋）", color: "#FFEE58" },
  semidetached_house: { name: "0707 城镇住宅用地（半独立住宅）", color: "#FFF59D" },
  static_caravan: { name: "0709 城镇住宅用地（移动房屋）", color: "#FFFDE7" },
  farm: { name: "01 耕地（农场建筑）", color: "#F5F8DC" },
  allotments: { name: "01 耕地（分配地）", color: "#F5F8DC" },
  farmyard: { name: "01 耕地（农家庭院）", color: "#F5F8DC" },
  greenhouse: { name: "01 耕地（温室）", color: "#E8F5E9" },
  plant_nursery: { name: "02 园地（苗圃）", color: "#BFE9AA" },
  nature_reserve: { name: "03 林地（自然保护区）", color: "#68B167" },
  grass: { name: "14 绿地与开敞空间用地", color: "#00FF00" },
  scrub: { name: "04 草地（灌木丛）", color: "#83C238" },
  heath: { name: "04 草地（荒地）", color: "#83C238" },
  administrative: { name: "0801 机关团体用地", color: "#EB46DA" },
  public_building: { name: "0801 机关团体用地", color: "#EB46DA" },
  police: { name: "0801 机关团体用地（警察）", color: "#EB46DA" },
  fire_station: { name: "0801 机关团体用地（消防）", color: "#EB46DA" },
  post_office: { name: "0801 机关团体用地（邮局）", color: "#EB46DA" },
  townhall: { name: "0801 机关团体用地（市政厅）", color: "#EB46DA" },
  courthouse: { name: "0801 机关团体用地（法院）", color: "#EB46DA" },
  research_institute: { name: "0802 科研用地", color: "#F0005C" },
  library: { name: "0803 文化用地", color: "#FF7F00" },
  theatre: { name: "0803 文化用地", color: "#FF7F00" },
  museum: { name: "0803 文化用地", color: "#FF7F00" },
  cinema: { name: "0803 文化用地（电影院）", color: "#FF7F00" },
  school: { name: "0804 教育用地", color: "#FF85C9" },
  university: { name: "0804 教育用地", color: "#FF85C9" },
  college: { name: "0804 教育用地", color: "#FF85C9" },
  kindergarten: { name: "0804 教育用地", color: "#FF85C9" },
  pitch: { name: "0805 体育用地", color: "#00A57C" },
  sports_centre: { name: "0805 体育用地", color: "#00A57C" },
  stadium: { name: "0805 体育用地", color: "#00A57C" },
  swimming_pool: { name: "0805 体育用地（游泳池）", color: "#00A57C" },
  hospital: { name: "0806 医疗卫生用地", color: "#FF7F7E" },
  clinic: { name: "0806 医疗卫生用地", color: "#FF7F7E" },
  doctors: { name: "0806 医疗卫生用地", color: "#FF7F7E" },
  pharmacy: { name: "0806 医疗卫生用地", color: "#FF7F7E" },
  social_facility: { name: "0807 社会福利用地", color: "#FF9F7F" },
  nursing_home: { name: "0807 社会福利用地", color: "#FF9F7F" },
  place_of_worship: { name: "1503 宗教用地", color: "#CC0066" },
  religious: { name: "1503 宗教用地", color: "#CC0066" },
  institutional: { name: "08 公共管理与公共服务用地", color: "#EB46DA" },
  retail: { name: "0901 商业用地", color: "#FF0000" },
  mall: { name: "0901 商业用地", color: "#FF0000" },
  supermarket: { name: "0901 商业用地（超市）", color: "#FF0000" },
  market: { name: "0901 商业用地（市场）", color: "#FF0000" },
  commercial: { name: "0901 商业用地", color: "#FF0000" },
  restaurant: { name: "0901 商业用地（餐饮）", color: "#E53935" },
  cafe: { name: "0901 商业用地（餐饮）", color: "#E53935" },
  fast_food: { name: "0901 商业用地（餐饮）", color: "#E53935" },
  bank: { name: "0902 商务金融用地", color: "#C00000" },
  office: { name: "0902 商务金融用地", color: "#C00000" },
  hotel: { name: "0904 其他商业服务业用地", color: "#91372A" },
  industrial: { name: "1001 工业用地", color: "#BB9674" },
  quarry: { name: "1002 采矿用地", color: "#9E6C54" },
  depot: { name: "1101 物流仓储用地", color: "#8761D3" },
  warehouse: { name: "1101 物流仓储用地", color: "#8761D3" },
  railway: { name: "1201 铁路用地", color: "#595959" },
  train_station: { name: "1201 铁路用地", color: "#595959" },
  highway: { name: "1202 公路用地", color: "#ADADAD" },
  airport: { name: "1203 机场用地", color: "#B7B7B7" },
  parking: { name: "1208 交通场站用地", color: "#D9D9D9" },
  bus_station: { name: "1208 交通场站用地", color: "#D9D9D9" },
  garage: { name: "1208 交通场站用地（车库）", color: "#BDBDBD" },
  garages: { name: "1208 交通场站用地（车库群）", color: "#9E9E9E" },
  shed: { name: "1208 交通场站用地（棚屋）", color: "#E0E0E0" },
  carport: { name: "1208 交通场站用地（车棚）", color: "#EEEEEE" },
  park: { name: "1401 公园绿地", color: "#00FF00" },
  garden: { name: "1401 公园绿地", color: "#00FF00" },
  playground: { name: "1401 公园绿地（游乐场）", color: "#00FF00" },
  golf_course: { name: "0805 体育用地（高尔夫）", color: "#00A57C" },
  greenfield: { name: "1401 公园绿地（待开发）", color: "#E8F5E9" },
  recreation_ground: { name: "1401 公园绿地（娱乐）", color: "#00FF00" },
  village_green: { name: "1401 公园绿地（村庄绿地）", color: "#00FF00" },
  square: { name: "1403 广场用地", color: "#ACFFCF" },
  military: { name: "1501 军事设施用地", color: "#859156" },
  prison: { name: "1501 军事设施用地（监狱）", color: "#859156" },
  cemetery: { name: "1506 殡葬用地", color: "#4F7E3E" },
  grave_yard: { name: "1506 殡葬用地", color: "#4F7E3E" },
  landfill: { name: "1507 垃圾处理用地", color: "#795548" },
  water: { name: "1701 河流水面", color: "#338EC0" },
  river: { name: "1701 河流水面", color: "#338EC0" },
  stream: { name: "1701 河流水面", color: "#338EC0" },
  salt_pond: { name: "1701 河流水面（盐池）", color: "#338EC0" },
  canal: { name: "1705 沟渠", color: "#9ABCE2" },
  drain: { name: "1705 沟渠", color: "#9ABCE2" },
  ditch: { name: "1705 沟渠", color: "#9ABCE2" },
  aerodrome: { name: "1203 机场用地", color: "#B7B7B7" },
  runway: { name: "1203 机场用地", color: "#B7B7B7" },
  terminal: { name: "1203 机场用地", color: "#B7B7B7" },
  station: { name: "1201 铁路用地", color: "#595959" },
  halt: { name: "1201 铁路用地", color: "#595959" },
  tram_stop: { name: "1208 交通场站用地", color: "#D9D9D9" },
  subway_entrance: { name: "1208 交通场站用地", color: "#D9D9D9" },
  construction: { name: "其他用地（在建）", color: "#E0E0E0" },
  service: { name: "其他用地（服务设施）", color: "#F5F5F5" },
  roof: { name: "其他用地（顶棚）", color: "#FAFAFA" },
  default: { name: "其他用地（未匹配分类）", color: "#E0E0E0" },
};

export const POI_COLORS: Record<AreaQueryType, string> = {
  all: "#9B59B6",
  building: "#A9A9A9",
  landuse: "#00BFFF",
  admin: "#595959",
  poi_restaurant: "#E74C3C",
  poi_medical: "#FF6B6B",
  poi_transport: "#F39C12",
  poi_shopping: "#27AE60",
  poi_education: "#3498DB",
  poi_sport: "#1ABC9C",
  poi_hotel: "#8E44AD",
  poi_all: "#9B59B6",
};

export const BUILDING_NAME_MAP: Record<string, string> = {
  yes: "未分类/未标注",
  apartments: "公寓建筑",
  dormitory: "宿舍建筑",
  detached: "独立住宅",
  house: "独户住宅",
  bungalow: "平房住宅",
  terrace: "排屋住宅",
  semidetached_house: "半独立住宅",
  static_caravan: "移动房屋",
  residential: "住宅建筑",
  commercial: "商业建筑",
  retail: "商业建筑（零售）",
  office: "办公建筑",
  industrial: "工业建筑",
  warehouse: "仓储建筑",
  garage: "车库/车棚",
  garages: "车库群",
  shed: "棚屋",
  carport: "车棚",
  roof: "顶棚结构",
  service: "服务性建筑",
  school: "学校建筑",
  university: "大学建筑",
  hospital: "医院建筑",
  clinic: "诊所建筑",
  hotel: "酒店建筑",
  mosque: "清真寺",
  church: "教堂",
  temple: "寺庙",
  synagogue: "犹太教堂",
  public: "公共建筑",
  government: "政府建筑",
  train_station: "火车站建筑",
  airport: "机场建筑",
  stadium: "体育场建筑",
  supermarket: "超市建筑",
  cinema: "电影院",
};
